# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 100

    php_errors:
        log: true
        
    cache:
        prefix_seed: my_app
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_doctrine_dbal_provider: 'doctrine.system_cache_pool'
        pools:
            doctrine.system_cache_pool:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
            api_cache_pool:
                adapter: cache.app
                default_lifetime: 3600
            
    validation:
        email_validation_mode: html5
        cache: validator.mapping.cache.adapter
        
    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/serializer/']
        
    rate_limiter:
        anonymous_api:
            policy: 'fixed_window'
            limit: 100
            interval: '60 minutes'
        
    router:
        utf8: true
        strict_requirements: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
