security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api_login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

        
            
            
        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            custom_authenticator: App\Security\AppAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: admin_dashboard
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine

    access_control:
        # API
        - { path: ^/api_login_check, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_ADMIN }
        # Pages publiques
        - { path: ^/$, roles: PUBLIC_ACCESS }  # Page d'accueil
        - { path: ^/article, roles: PUBLIC_ACCESS }  # Liste des articles et détails
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Pages sécurisées
        - { path: ^/admin, roles: ROLE_ADMIN }  # Interface d'administration
        - { path: ^/profile, roles: ROLE_USER }  # Profil utilisateur

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

monolog:
    channels: ['security']
    handlers:
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug
