POST http://localhost:8000/api_login_check
Content-Type: application/json
Accept: application/json

{
    "email": "admin2@top.com",
    "password": "123admin2"
}
###
GET http://localhost:8000/api/comments/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDE1NTQ1MDgsImV4cCI6MTc0MTU1ODEwOCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJlbWFpbCI6ImFkbWluMkB0b3AuY29tIn0.C7LKBx4ombbzSnFMl0x-SyqJjsxFaTvkIUCs3hONkB18A0Tgrn8o-ADJqvTdMk3ECuXtewyML8w9_b3dJjQVtvgYt54G1GZYXY-z-Gnla3RjTQmPCpQzoU_59LMYiIivcKG5L-uAbIL-tn2bsbWFuFRjSl1fQN4IIi3x4-_xFkp6QpwyRJib70cx-zKOE0Ew2_2oXe3Py23t1XGSBMgawZg2x9ty8GF6FdNHPhv92y3nQHqdx8and93WAKLq16q6qwy9Yb9BKix9uZp1MXd9bBYYMYuqDBdetiophs2MbirWAawNDtNOiwPcVh9BOcG86JpIlk0FGY-midpCJM07qqYQYJZdOsVccsqVPkglIq5QOqy8VzU500zsk1YOCs52NrHBFmdig7iEtTZ9b72btuyeQtV-uQW49altXhy17mRtgIQRh46cthdBtgNrBXPz1V8QeKErYGvP8HeA02YCHyLFdbHa-TBwjdreW0UTHq761uKb_xbKy3AfqTOqRIOOUIzu0Ag1_NDEqCUv9Itefjz7r_qjfVRIegoJCSYKgJKek00cZET_M5QYLioU2M3RaSWVNf2AGK78NYN4rmHjD-dG3FuiKhW7BEDaRKnPrWEBVlgRkL04PBaVbHYlkdKH_mZQ-_toVM7sX4MxmPg1ORjbnrJyGWorZglEircKdoU

###
GET http://localhost:8000/api/comments/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDE1NTQ1MDgsImV4cCI6MTc0MTU1ODEwOCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJlbWFpbCI6ImFkbWluMkB0b3AuY29tIn0.C7LKBx4ombbzSnFMl0x-SyqJjsxFaTvkIUCs3hONkB18A0Tgrn8o-ADJqvTdMk3ECuXtewyML8w9_b3dJjQVtvgYt54G1GZYXY-z-Gnla3RjTQmPCpQzoU_59LMYiIivcKG5L-uAbIL-tn2bsbWFuFRjSl1fQN4IIi3x4-_xFkp6QpwyRJib70cx-zKOE0Ew2_2oXe3Py23t1XGSBMgawZg2x9ty8GF6FdNHPhv92y3nQHqdx8and93WAKLq16q6qwy9Yb9BKix9uZp1MXd9bBYYMYuqDBdetiophs2MbirWAawNDtNOiwPcVh9BOcG86JpIlk0FGY-midpCJM07qqYQYJZdOsVccsqVPkglIq5QOqy8VzU500zsk1YOCs52NrHBFmdig7iEtTZ9b72btuyeQtV-uQW49altXhy17mRtgIQRh46cthdBtgNrBXPz1V8QeKErYGvP8HeA02YCHyLFdbHa-TBwjdreW0UTHq761uKb_xbKy3AfqTOqRIOOUIzu0Ag1_NDEqCUv9Itefjz7r_qjfVRIegoJCSYKgJKek00cZET_M5QYLioU2M3RaSWVNf2AGK78NYN4rmHjD-dG3FuiKhW7BEDaRKnPrWEBVlgRkL04PBaVbHYlkdKH_mZQ-_toVM7sX4MxmPg1ORjbnrJyGWorZglEircKdoU

###

PUT http://localhost:8000/api/comments/1
Content-Type: application/json
Accept: application/text/text/html
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDE1NTQ1MDgsImV4cCI6MTc0MTU1ODEwOCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJlbWFpbCI6ImFkbWluMkB0b3AuY29tIn0.C7LKBx4ombbzSnFMl0x-SyqJjsxFaTvkIUCs3hONkB18A0Tgrn8o-ADJqvTdMk3ECuXtewyML8w9_b3dJjQVtvgYt54G1GZYXY-z-Gnla3RjTQmPCpQzoU_59LMYiIivcKG5L-uAbIL-tn2bsbWFuFRjSl1fQN4IIi3x4-_xFkp6QpwyRJib70cx-zKOE0Ew2_2oXe3Py23t1XGSBMgawZg2x9ty8GF6FdNHPhv92y3nQHqdx8and93WAKLq16q6qwy9Yb9BKix9uZp1MXd9bBYYMYuqDBdetiophs2MbirWAawNDtNOiwPcVh9BOcG86JpIlk0FGY-midpCJM07qqYQYJZdOsVccsqVPkglIq5QOqy8VzU500zsk1YOCs52NrHBFmdig7iEtTZ9b72btuyeQtV-uQW49altXhy17mRtgIQRh46cthdBtgNrBXPz1V8QeKErYGvP8HeA02YCHyLFdbHa-TBwjdreW0UTHq761uKb_xbKy3AfqTOqRIOOUIzu0Ag1_NDEqCUv9Itefjz7r_qjfVRIegoJCSYKgJKek00cZET_M5QYLioU2M3RaSWVNf2AGK78NYN4rmHjD-dG3FuiKhW7BEDaRKnPrWEBVlgRkL04PBaVbHYlkdKH_mZQ-_toVM7sX4MxmPg1ORjbnrJyGWorZglEircKdoU

{
    "content": "New comment content",
    "status": "pending"
}


