POST http://localhost:8000/api_login_check
Content-Type: application/json
Accept: application/json

{
    "email": "admin2@top.com",
    "password": "123admin2"
}
###
GET http://localhost:8000/api/comments/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDE0MzYyNTIsImV4cCI6MTc0MTQzOTg1Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJlbWFpbCI6ImFkbWluMkB0b3AuY29tIn0.Me-_QaT5ObLCz7PbtyB02fbF7PFV3wF4duwxmCh4h3epPxGTWON69KWy3EG8LkSpOySU4Z1j75pQKa-BDqg7JNPmk_LviCy0ZBnBcpgWxq0OFt3YHcwj9NQeIj-QzdOUMT9NC4V1xS8AjrYBJmYHqJDhQWRcNKfdhJpVGJf_5lSP02ndJslnoDCr117QWqrtdDC7TZietdp4BHFCMrmgr0aQdwFWcAem4qcTuaGdgrwMS4-e6VfBdPneoYpJC5XQLnE_m6EgVsX9Zg5iWjDfZgJkNpEHJy4_PxgQAoiy7hk7MRBdH0x06B9YofTr-IeEj6h7nbNrXIyVYyoHBm32FT-0Af2OPvG2qGE23vzpjykPcf-hlSWUCaEaDSZ98aGvGj_WexpN6MAyGKVM160igc6kh_0CBk1T-NyZiGpb0WsdYydzHTfJLNFLGvZjeFGI01KJ6lCIp6VLGju--7lpPe3qT2sjTk6qIA0dkPFt6Akd6-0TlqrMXMgBBF04x3K9bVCSWs1fd2giaJ9LJukpqNEnop5778TEOyXryJLGksOM1a1En5GN5rMtVqpaDYjMgctamHT-xcnh281OLOqqNhs5gNnpkLiuDkvkCEgmicTgG2HjLFoNNfnciSTibOkAfELKUmCrL58b8LX_yjz6r2_6Ra8MkoIQdAPYnhETM4A
